Update to LLVM 14 (C++17 support)
unikraft/lib-libcxxabi pull request #4
Opened 2023-05-05 20:14 UTC by andreittr

Update libcxxabi to 14.0.6.
This is part of a patch set consisting of:
 - [libcxx](https://github.com/unikraft/lib-libcxx/pull/28)
 - libcxxabi
 - lib-compiler-rt
 - libunwind
 - [musl](https://github.com/unikraft/lib-musl/pull/45)

2023-05-18 18:13 UTC, StefanJum requested changes
@andreittr please add some descriptions to the commits.

2023-05-27 12:17 UTC, StefanJum approved these changes
All good, thanks. Needs [unikraft/913](https://github.com/unikraft/unikraft/pull/913) to be integrated for it to work on `arm64` + `clang`.
Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>

2023-05-27 12:31 UTC, mariasfiraiala approved these changes
Nice work @andreittr! Thank you for this, all good on my side.

Reviewed-by: Maria Sfiraiala <maria.sfiraiala@gmail.com>

2023-06-01 14:24 UTC, razvand commented
Hi, @andreittr. Please prefix the 2nd commit in the PR with the `Makefile.uk` prefix. Everything else works.

After that, @eduardvintila, please approve the PR.

2023-06-01 15:37 UTC, razvand approved these changes
I tested this as well, and it works as expected. Thanks, @andreittr.

Reviewed-by: Razvan Deaconescu <razvand@unikraft.io>

2023-06-01 19:17 UTC, eduardvintila approved these changes
Thanks, everyone!

Approved-by: Eduard Vintilă <eduard.vintila47@gmail.com>

2023-06-01 19:28 UTC, closed without merging